version: '2'

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=lees.org.uk
      - SUBDOMAINS=wordpress
      - VALIDATION=http
      - EMAIL=william@lees.org.uk  #optional
      - ONLY_SUBDOMAINS=true #optional
#      - EXTRA_DOMAINS= #optional
      - STAGING=true #optional
    volumes:
      - /root/digby_infra/config/nginx:/config
      - /root/digby_infra/config/wordpress/html:/wordpress_www
      - /root/digby_docker/config/nginx/www:/vdjbase_www
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=gsdfgtwevdfg
      - TZ=Europe/London
    volumes:
      - /root/digby_infra/config/mysql:/config
    restart: unless-stopped
  wordpress:
    image: 5-fpm-alpine
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST: mariadb
      - MYSQL_ROOT_PASSWORD: gsdfgtwevdfg
      - WORDPRESS_DB_NAME: wordpress
      - WORDPRESS_DB_USER: wordpress
      - WORDPRESS_DB_PASSWORD: dfoiweoriw
      - WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - /root/digby_infra/config/wordpress/html:/var/www/html
    depends_on:
      - mariadb
    restart: unless-stopped
networks:
    default:
        name: digby_network
